<!-- Header -->
<header>
    <br> <br> <br> <br>
    <div class="container">

        <?php

        $form = $this->form;
        $form->setAttribute('action',
            $this->url('blogger',
                array('action' => 'add')
            ));

        $form->setAttribute('method', 'post');
        $form->setAttribute('class', 'form-horizontal');
        $form->setAttribute('role', 'form');

        ?>

        <?php

        $form->prepare();

        ?>

        <div class="jumbotron text-primary">
            <ul class="nav nav-pills">
                <li><a class="text-primary"
                       href="<?php echo $this->url('blogger-author', array('action' => 'index')); ?>">View Authors</a>
                </li>
                <li><a class="text-primary"
                       href="<?php echo $this->url('blogger-author', array('action' => 'add')); ?>">Add Authors</a></li>
                <li><a class="text-primary" href="<?php echo $this->url('blogger', array('action' => 'view')); ?>">View
                        Post</a></li>
                <li class="active"><a class="text-primary"
                                      href="<?php echo $this->url('blogger', array('action' => 'add')); ?>">Add Post</a>
                </li>
                <li><a class="text-primary" href="<?php echo $this->url('blogger', array('action' => 'index')); ?>">Indexer
                        Post</a></li>
            </ul>

            <div class="normal-text">
                <center>
                    <?php echo $this->form()->openTag($form); ?>




                    <?php foreach ($form as $element) : ?>

                        <div style="width: 530px;"
                             class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
                            <?php
                            if ('submit' != $element->getAttribute('type')) { ?>
                            <label style="width: 200px; text-align:right;"
                                   class="col-sm-2 control-label"><?php echo $element->getLabel() ?></label>
                            <div class="col-sm-10" style="width: 330px;">

                                <?php
                                $element->setAttribute('class', 'form-control')
                                    ->setAttribute('placeholder', $element->getLabel());
                                } else {
                                    $element->setAttribute('class', 'btn btn-success');
                                    // Somehow it remaines value add so we set it manual here.
                                    $element->setAttribute('value', $this->translate('Send'));
                                }
                                if ($element instanceof Zend\Form\Element\Captcha) {
                                    echo $this->formCaptcha($element);
                                } else {
                                    echo $this->formElement($element);
                                }
                                if ($this->formElementErrors($element)) : ?>
                                    <?php
                                    echo $this->formElementErrors()
                                        ->setMessageOpenFormat('<p style="font-size:12px;" class="help-block"><b>')
                                        ->setMessageSeparatorString('</b></p><p class="help-block">')
                                        ->setMessageCloseString('</p>')
                                        ->render($element);
                                    ?>
                                <?php endif; ?>
                            </div>
                        </div>

                        <?php
                    endforeach; ?>

                    <?php if ($this->redirect): ?>
                        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>"/>
                    <?php endif ?>
                    <?php echo $this->form()->closeTag() ?>
                </center>
            </div>
        </div>
    </div>
    </div>
</header>     

