<!-- Header -->
<header>
    <br> <br> <br> <br>
    <div class="container">
        <div class="jumbotron transparent  text-primary">
            <h2>Convertor</h2>
            <div class="normal-text">
                <p>Choose which provider</p><br>
                <ul class="nav nav-pills">
                    <li class="active"><a href="<?php echo $this->url("converter") ?>">Home</a></li>
                    <li><a class="text-primary" href="<?php echo $this->url("webservicex") ?>">Webservicex</a></li>
                    <li><a class="text-primary" href="<?php echo $this->url("kowabunga") ?>">Kowabunga</a></li>
                </ul>
            </div>

        </div>
    </div>
    </div>
</header>    