<!-- Header -->
<header>
    <br> <br> <br> <br>
    <div class="container">

        <!-- Test if the User is connected -->
        <?php if (!$this->zfcUserIdentity()): ?>
            <!-- display the login form -->
            <?php //echo $this->zfcUserLoginWidget(array('redirect'=>'application')); ?>
        <?php else: ?>
            <!-- display the 'display name' of the user -->
            <?php //echo $this->zfcUserIdentity()->getDisplayname(); ?>
        <?php endif ?>

        <?php
        /*
         *
         *
         *
         */
        // Set classes we need in the front view.
        //$country = new Converterapp\Form\KowabungaController;
        $country = new Converterapp\Form\KowabungaForm;


        if (isset($this->Values)) {

            $from_currency = trim($this->Values[value][fromcurrency]);
            $tocurrency = trim($this->Values[value][tocurrency]);
            $lastupdate = trim($this->Values[value][dateupdate]);
            $amount = trim($this->Values[value][amount]);
            //$amount = number_format($amount,5,",",".");
            $myamount = trim($this->Values[value][postamount]);
            $rate = trim($this->Values[value][rate]);
            //$rate = number_format($rate,5,",",".");
            $country_array = $country->getCountryCodes();

        }

        // Prepare the form already
        $form = $this->form;
        $form->setAttribute('action', $this->url('kowabunga'));
        $form->setAttribute('method', 'post');

        $form->prepare();

        ?>


        <script>

            $(function () {

                $("#datetime").datepicker({
                    dateFormat: 'yy-mm-dd',
                    showOtherMonths: true,
                    selectOtherMonths: true,
                });


            });

        </script>


        <div class="jumbotron text-primary">
            <h2>
                <?php echo $this->translate('Convertor') ?>
            </h2>
            <div class="normal-text">
                <p>
                    <?php echo $this->translate('Choose which provider') ?>
                </p>
                <br>
                <ul class="nav nav-pills">
                    <li><a class="text-primary"
                           href="<?php echo $this->url("converter") ?>">Home</a></li>
                    <li><a class="text-primary"
                           href="<?php echo $this->url("webservicex") ?>">Webservicex</a></li>
                    <li class="active"><a href="<?php echo $this->url("kowabunga") ?>">Kowabunga</a>
                    </li>
                </ul>


                <?php
                /*
                 * Dump here the selection and calculations.
                 *
                 *
                 */


                if (isset($this->Values)) {
                    $from = $country_array[$from_currency];
                    $to = $country_array[$tocurrency];
                    //$rate = $country_array[$rate];
                    if ($lastupdate) {
                        echo '<p>Last Update date on : ' . $lastupdate . '</p>';
                    }
                    if ($from) {

                        echo '<div style="width: 650px;" class="list-group">
	  <a href="#" class="list-group-item active">
	  <h4 class="list-group-item-heading">' . $this->translate('Converting') . ' : ' . $from . '  -> ' . $to . '</h4>
	  </a>
	  <p class="list-group-item-text">' . $from . ' : ' . $myamount . '</p>
	  <p class="list-group-item-text">' . $to . ' : ' . $amount . '</p>
	  <p class="list-group-item-text">' . $this->translate('Rate') . ' : ' . $rate . '</p>
	</div>';


                    }

                }

                ?>
                <?php echo $this->form()->openTag($form); ?>
                <?php foreach ($form as $element) : ?>

                    <div style="width: 530px;"
                         class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
                        <?php
                        if ('submit' != $element->getAttribute('type')) { ?>
                        <label style="width: 200px; text-align: right;"
                               class="col-sm-2 control-label"><?php echo $element->getLabel() ?> </label>
                        <div class="col-sm-10" style="width: 330px;">

                            <?php
                            $element->setAttribute('class', 'form-control')
                                ->setAttribute('placeholder', $element->getLabel());
                            } else {
                                $element->setAttribute('class', 'btn btn-success');
                                // Somehow it remaines value add so we set it manual here.
                                $element->setAttribute('value', $this->translate('Convert'));
                            }
                            if ($element instanceof Zend\Form\Element\Captcha) {
                                echo $this->formCaptcha($element);
                            } else {
                                echo $this->formElement($element);
                            }
                            if ($this->formElementErrors($element)) : ?>
                                <?php
                                echo $this->formElementErrors()
                                    ->setMessageOpenFormat('<p style="font-size:12px;" class="help-block"><b>')
                                    ->setMessageSeparatorString('</b></p><p class="help-block">')
                                    ->setMessageCloseString('</p>')
                                    ->render($element);
                                ?>
                            <?php endif; ?>
                        </div>
                    </div>

                    <?php
                endforeach; ?>

                <?php if ($this->redirect): ?>
                    <input type="hidden" name="redirect"
                           value="<?php echo $this->escapeHtml($this->redirect) ?>"/>
                <?php endif ?>
                <?php echo $this->form()->closeTag() ?>
            </div>
        </div>

    </div>
    </div>
</header>    
