<?php echo $this->doctype(); ?>

<?php echo $this->meta_title; ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Burnworld'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                       // ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/agency.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
          //  ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

<!-- Bootstrap Core CSS -->

    <!-- Custom CSS -->
	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
  
  
    <!-- Custom Fonts -->
    <link href="font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    
</head>

<body id="page-top" class="index">
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/nl_NL/sdk.js#xfbml=1&appId=1507985842780251&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<!-- Navigation -->
     <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="<?php echo $this->url('home')  ?>#page-top"><span class="glyphicon glyphicon-off"></span>&nbsp;<?php echo $this->translate('Burnworld') ?></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="<?php echo $this->url('home') ?>#page-top"><?php echo $this->translate('Start') ?></a>
                    </li>
                   <!--  <li>
                        <a class="page-scroll" href="</a>
                    </li> -->
                    <li>
                        <a class="page-scroll" href="<?php echo $this->url('about') ?>#about"><?php echo $this->translate('About') ?></a>
                    </li>
                    <li>
                    <!-- 
                    
        		
                    
                     -->
                        <a class="page-scroll" href="<?php echo $this->url('contact', array('action'=>'add')) ?>#contact"><?php echo $this->translate('Contact Us') ?></a>
                    </li>
                     
                     <?php  if($this->zfcUserIdentity()):?>     
                     <li class="dropdown">
                        
			<?php print '<a class="dropdown-toggle" data-toggle="dropdown" href="'.$this->url('zfcuser/logout').'">'.$this->translate('Sign Out').'<span class="caret"></span></a>'; ?>
            
			<ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
			<li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          	</ul>
        	 </li>
      		</ul>
        
			<?php else: ?>
				<li>    
            <?php print '<a class="page-scroll" href="'.$this->url('zfcuser/login').'">'.$this->translate('Sign In').'</a>';	?>
            </li>
                </ul>
            <?php endif;?>
			?>
                    
                
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    
        <!-- Header -->
    <header>
        <br><br><br><br>
        <div class="container">
           	
    					
				<?php  echo $this->content; ?>
          
                
        	
   </div>
   </header>
   
       <!-- Services Section -->
    <section id="services">
        <div class="container">
   				<div class="row">
   
               </div>
        </div>
    </section>
   <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                <div class="fb-like" data-href="<?php echo $this->serverUrl().$this->url() ?>" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
                
           
			
                    <span class="copyright">Copyright &copy; Ignitions <?php echo date('Y')?></span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    
   
    
        
    

</body>

</html>
